#ifndef PTREPLAY_INTERFACE_DEF_H
#define PTREPLAY_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.7.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct PTReplayIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct PTReplayIFace *Self);
	ULONG APICALL (*Release)(struct PTReplayIFace *Self);
	void APICALL (*Expunge)(struct PTReplayIFace *Self);
	struct Interface * APICALL (*Clone)(struct PTReplayIFace *Self);
	struct Module * APICALL (*PTLoadModule)(struct PTReplayIFace *Self, STRPTR name);
	VOID APICALL (*PTUnloadModule)(struct PTReplayIFace *Self, struct Module * module);
	ULONG APICALL (*PTPlay)(struct PTReplayIFace *Self, struct Module * module);
	ULONG APICALL (*PTStop)(struct PTReplayIFace *Self, struct Module * module);
	ULONG APICALL (*PTPause)(struct PTReplayIFace *Self, struct Module * module);
	ULONG APICALL (*PTResume)(struct PTReplayIFace *Self, struct Module * module);
	VOID APICALL (*PTFade)(struct PTReplayIFace *Self, struct Module * module, UBYTE speed);
	VOID APICALL (*PTSetVolume)(struct PTReplayIFace *Self, struct Module * module, UBYTE vol);
	UBYTE APICALL (*PTSongPos)(struct PTReplayIFace *Self, struct Module * module);
	UBYTE APICALL (*PTSongLen)(struct PTReplayIFace *Self, struct Module * module);
	UBYTE APICALL (*PTSongPattern)(struct PTReplayIFace *Self, struct Module * module, UWORD Pos);
	UBYTE APICALL (*PTPatternPos)(struct PTReplayIFace *Self, struct Module * Module);
	APTR APICALL (*PTPatternData)(struct PTReplayIFace *Self, struct Module * Module, UBYTE Pattern, UBYTE Row);
	void APICALL (*PTInstallBits)(struct PTReplayIFace *Self, struct Module * Module, BYTE Restart, BYTE NextPattern, BYTE NextRow, BYTE Fade);
	struct Module * APICALL (*PTSetupMod)(struct PTReplayIFace *Self, APTR ModuleFile);
	void APICALL (*PTFreeMod)(struct PTReplayIFace *Self, struct Module * Module);
	void APICALL (*PTStartFade)(struct PTReplayIFace *Self, struct Module * Module, UBYTE speed);
	void APICALL (*PTOnChannel)(struct PTReplayIFace *Self, struct Module * Module, BYTE Channels);
	void APICALL (*PTOffChannel)(struct PTReplayIFace *Self, struct Module * Module, BYTE Channels);
	void APICALL (*PTSetPos)(struct PTReplayIFace *Self, struct Module * Module, UBYTE Pos);
	void APICALL (*PTSetPri)(struct PTReplayIFace *Self, BYTE Pri);
	BYTE APICALL (*PTGetPri)(struct PTReplayIFace *Self);
	BYTE APICALL (*PTGetChan)(struct PTReplayIFace *Self);
	struct PTSample * APICALL (*PTGetSample)(struct PTReplayIFace *Self, struct Module * Module, WORD Nr);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* PTREPLAY_INTERFACE_DEF_H */
