#ifndef INLINE4_PTREPLAY_H
#define INLINE4_PTREPLAY_H

/*
** This file was auto generated by idltool 52.7.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#include <interfaces/ptreplay.h>

/* Inline macros for Interface "main" */
#define PTLoadModule(name) IPTReplay->PTLoadModule((name)) 
#define PTUnloadModule(module) IPTReplay->PTUnloadModule((module)) 
#define PTPlay(module) IPTReplay->PTPlay((module)) 
#define PTStop(module) IPTReplay->PTStop((module)) 
#define PTPause(module) IPTReplay->PTPause((module)) 
#define PTResume(module) IPTReplay->PTResume((module)) 
#define PTFade(module, speed) IPTReplay->PTFade((module), (speed)) 
#define PTSetVolume(module, vol) IPTReplay->PTSetVolume((module), (vol)) 
#define PTSongPos(module) IPTReplay->PTSongPos((module)) 
#define PTSongLen(module) IPTReplay->PTSongLen((module)) 
#define PTSongPattern(module, Pos) IPTReplay->PTSongPattern((module), (Pos)) 
#define PTPatternPos(Module) IPTReplay->PTPatternPos((Module)) 
#define PTPatternData(Module, Pattern, Row) IPTReplay->PTPatternData((Module), (Pattern), (Row)) 
#define PTInstallBits(Module, Restart, NextPattern, NextRow, Fade) IPTReplay->PTInstallBits((Module), (Restart), (NextPattern), (NextRow), (Fade)) 
#define PTSetupMod(ModuleFile) IPTReplay->PTSetupMod((ModuleFile)) 
#define PTFreeMod(Module) IPTReplay->PTFreeMod((Module)) 
#define PTStartFade(Module, speed) IPTReplay->PTStartFade((Module), (speed)) 
#define PTOnChannel(Module, Channels) IPTReplay->PTOnChannel((Module), (Channels)) 
#define PTOffChannel(Module, Channels) IPTReplay->PTOffChannel((Module), (Channels)) 
#define PTSetPos(Module, Pos) IPTReplay->PTSetPos((Module), (Pos)) 
#define PTSetPri(Pri) IPTReplay->PTSetPri((Pri)) 
#define PTGetPri() IPTReplay->PTGetPri() 
#define PTGetChan() IPTReplay->PTGetChan() 
#define PTGetSample(Module, Nr) IPTReplay->PTGetSample((Module), (Nr)) 

#endif /* INLINE4_PTREPLAY_H */
