/*
** This file was automatically generated by fdtrans 51.19.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifdef __USE_INLINE__
#undef __USE_INLINE__
#endif
#ifndef __NOGLOBALIFACE__
#define __NOGLOBALIFACE__
#endif

#include <exec/interfaces.h>
#include <exec/libraries.h>
#include <exec/emulation.h>
#include <interfaces/exec.h>
#include <interfaces/ptreplay.h>
#include <proto/ptreplay.h>


static inline int8  convert_int8 (uint32 x) { return x; }
static inline int16 convert_int16(uint32 x) { return x; }


STATIC struct Library * stub_OpenPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

	return Self->Open(0);
}
STATIC CONST struct EmuTrap stub_Open = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_OpenPPC };

STATIC APTR stub_ClosePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct LibraryManagerInterface *Self = (struct LibraryManagerInterface *) ExtLib->ILibrary;

	return Self->Close();
}
STATIC CONST struct EmuTrap stub_Close = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ClosePPC };

STATIC APTR stub_ExpungePPC(ULONG *regarray __attribute__((unused)))
{
	return NULL;
}
STATIC CONST struct EmuTrap stub_Expunge = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_ExpungePPC };

STATIC ULONG stub_ReservedPPC(ULONG *regarray __attribute__((unused)))
{
	return 0UL;
}
STATIC CONST struct EmuTrap stub_Reserved = { TRAPINST, TRAPTYPE, stub_ReservedPPC };

static struct Module * stub_PTLoadModulePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTLoadModule(
		(STRPTR)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_PTLoadModule = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTLoadModulePPC };

static VOID stub_PTUnloadModulePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	Self->PTUnloadModule(
		(struct Module *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_PTUnloadModule = { TRAPINST, TRAPTYPENR, (ULONG (*)(ULONG *))stub_PTUnloadModulePPC };

static ULONG stub_PTPlayPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTPlay(
		(struct Module *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_PTPlay = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTPlayPPC };

static ULONG stub_PTStopPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTStop(
		(struct Module *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_PTStop = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTStopPPC };

static ULONG stub_PTPausePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTPause(
		(struct Module *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_PTPause = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTPausePPC };

static ULONG stub_PTResumePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTResume(
		(struct Module *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_PTResume = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTResumePPC };

static VOID stub_PTFadePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	Self->PTFade(
		(struct Module *)regarray[8],
		(UBYTE)(regarray[0] & 0xff)
	);
}
STATIC CONST struct EmuTrap stub_PTFade = { TRAPINST, TRAPTYPENR, (ULONG (*)(ULONG *))stub_PTFadePPC };

static VOID stub_PTSetVolumePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	Self->PTSetVolume(
		(struct Module *)regarray[8],
		(UBYTE)(regarray[0] & 0xff)
	);
}
STATIC CONST struct EmuTrap stub_PTSetVolume = { TRAPINST, TRAPTYPENR, (ULONG (*)(ULONG *))stub_PTSetVolumePPC };

static UBYTE stub_PTSongPosPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTSongPos(
		(struct Module *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_PTSongPos = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTSongPosPPC };

static UBYTE stub_PTSongLenPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTSongLen(
		(struct Module *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_PTSongLen = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTSongLenPPC };

static UBYTE stub_PTSongPatternPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTSongPattern(
		(struct Module *)regarray[8],
		(UWORD)(regarray[0] & 0xffff)
	);
}
STATIC CONST struct EmuTrap stub_PTSongPattern = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTSongPatternPPC };

static UBYTE stub_PTPatternPosPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTPatternPos(
		(struct Module *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_PTPatternPos = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTPatternPosPPC };

static APTR stub_PTPatternDataPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTPatternData(
		(struct Module *)regarray[8],
		(UBYTE)(regarray[0] & 0xff),
		(UBYTE)(regarray[1] & 0xff)
	);
}
STATIC CONST struct EmuTrap stub_PTPatternData = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTPatternDataPPC };

static void stub_PTInstallBitsPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	Self->PTInstallBits(
		(struct Module *)regarray[8],
		(BYTE)convert_int8(regarray[0]),
		(BYTE)convert_int8(regarray[1]),
		(BYTE)convert_int8(regarray[2]),
		(BYTE)convert_int8(regarray[3])
	);
}
STATIC CONST struct EmuTrap stub_PTInstallBits = { TRAPINST, TRAPTYPENR, (ULONG (*)(ULONG *))stub_PTInstallBitsPPC };

static struct Module * stub_PTSetupModPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTSetupMod(
		(APTR)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_PTSetupMod = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTSetupModPPC };

static void stub_PTFreeModPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	Self->PTFreeMod(
		(struct Module *)regarray[8]
	);
}
STATIC CONST struct EmuTrap stub_PTFreeMod = { TRAPINST, TRAPTYPENR, (ULONG (*)(ULONG *))stub_PTFreeModPPC };

static void stub_PTStartFadePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	Self->PTStartFade(
		(struct Module *)regarray[8],
		(UBYTE)(regarray[0] & 0xff)
	);
}
STATIC CONST struct EmuTrap stub_PTStartFade = { TRAPINST, TRAPTYPENR, (ULONG (*)(ULONG *))stub_PTStartFadePPC };

static void stub_PTOnChannelPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	Self->PTOnChannel(
		(struct Module *)regarray[8],
		(BYTE)convert_int8(regarray[0])
	);
}
STATIC CONST struct EmuTrap stub_PTOnChannel = { TRAPINST, TRAPTYPENR, (ULONG (*)(ULONG *))stub_PTOnChannelPPC };

static void stub_PTOffChannelPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	Self->PTOffChannel(
		(struct Module *)regarray[8],
		(BYTE)convert_int8(regarray[0])
	);
}
STATIC CONST struct EmuTrap stub_PTOffChannel = { TRAPINST, TRAPTYPENR, (ULONG (*)(ULONG *))stub_PTOffChannelPPC };

static void stub_PTSetPosPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	Self->PTSetPos(
		(struct Module *)regarray[8],
		(UBYTE)(regarray[0] & 0xff)
	);
}
STATIC CONST struct EmuTrap stub_PTSetPos = { TRAPINST, TRAPTYPENR, (ULONG (*)(ULONG *))stub_PTSetPosPPC };

static void stub_PTSetPriPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	Self->PTSetPri(
		(BYTE)convert_int8(regarray[0])
	);
}
STATIC CONST struct EmuTrap stub_PTSetPri = { TRAPINST, TRAPTYPENR, (ULONG (*)(ULONG *))stub_PTSetPriPPC };

static BYTE stub_PTGetPriPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTGetPri(
	);
}
STATIC CONST struct EmuTrap stub_PTGetPri = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTGetPriPPC };

static BYTE stub_PTGetChanPPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTGetChan(
	);
}
STATIC CONST struct EmuTrap stub_PTGetChan = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTGetChanPPC };

static struct PTSample * stub_PTGetSamplePPC(ULONG *regarray)
{
	struct Library *Base = (struct Library *) regarray[REG68K_A6/4];
	struct ExtendedLibrary *ExtLib = (struct ExtendedLibrary *) ((ULONG)Base + Base->lib_PosSize);
	struct PTReplayIFace *Self = (struct PTReplayIFace *) ExtLib->MainIFace;

	return Self->PTGetSample(
		(struct Module *)regarray[8],
		(WORD)convert_int16(regarray[0])
	);
}
STATIC CONST struct EmuTrap stub_PTGetSample = { TRAPINST, TRAPTYPE, (ULONG (*)(ULONG *))stub_PTGetSamplePPC };

CONST CONST_APTR VecTable68K[] =
{
	&stub_Open,
	&stub_Close,
	&stub_Expunge,
	&stub_Reserved,
	&stub_PTLoadModule,
	&stub_PTUnloadModule,
	&stub_PTPlay,
	&stub_PTStop,
	&stub_PTPause,
	&stub_PTResume,
	&stub_PTFade,
	&stub_PTSetVolume,
	&stub_PTSongPos,
	&stub_PTSongLen,
	&stub_PTSongPattern,
	&stub_PTPatternPos,
	&stub_PTPatternData,
	&stub_PTInstallBits,
	&stub_PTSetupMod,
	&stub_PTFreeMod,
	&stub_PTStartFade,
	&stub_PTOnChannel,
	&stub_PTOffChannel,
	&stub_PTSetPos,
	&stub_PTSetPri,
	&stub_PTGetPri,
	&stub_PTGetChan,
	&stub_PTGetSample,
	(CONST_APTR)-1
};
